<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Check, Clock, Lock, Refresh } from '@element-plus/icons-vue'
import { request, type AccessApplication, type Page } from '../api/http'

const loading = ref(false)
const page = ref(1)
const data = ref<Page<AccessApplication>>({ items: [], total: 0, page: 1, pageSize: 10 })
const filters = reactive({ status: '' })
const showCreate = ref(false)
const creating = ref(false)
const createForm = reactive({ purpose: '', useType: 'READ', startAt: '', dueAt: '', versionIds: '' })
const statusLabel: Record<string, string> = { DRAFT: '草稿', PENDING_APPROVAL: '待授权', APPROVED: '已授权', IN_USE: '使用中', RETURNED: '已归还', ABNORMAL: '异常' }
async function load() { loading.value = true; try { data.value = await request<Page<AccessApplication>>({ url: '/archive-access', params: { page: page.value, pageSize: 10, status: filters.status || undefined } }) } catch (e) { ElMessage.error(e instanceof Error ? e.message : '授权列表加载失败') } finally { loading.value = false } }
async function action(item: AccessApplication, name: string, body?: unknown) { try { await request<AccessApplication>({ url: `/archive-access/${item.id}/${name}`, method: 'POST', data: body }); ElMessage.success('状态已更新'); load() } catch (e) { ElMessage.error(e instanceof Error ? e.message : '状态更新失败') } }
async function returnItem(item: AccessApplication) { const remark = await ElMessageBox.prompt('填写归还说明', '归还档案', { inputPlaceholder: '如发现缺页或损坏，请说明' }).then((r) => r.value).catch(() => null); if (remark === null) return; action(item, 'return', { abnormal: false, remark }) }
async function createAccess() { const ids = createForm.versionIds.split(',').map((value) => Number(value.trim())).filter(Boolean); if (!createForm.purpose || !ids.length || !createForm.dueAt) return ElMessage.warning('请完整填写用途、版本 ID 和归还时间'); creating.value = true; try { await request<AccessApplication>({ url: '/archive-access', method: 'POST', data: { purpose: createForm.purpose, useType: createForm.useType, startAt: createForm.startAt || undefined, dueAt: createForm.dueAt, versionIds: ids } }); showCreate.value = false; ElMessage.success('授权申请已创建'); load() } catch (e) { ElMessage.error(e instanceof Error ? e.message : '创建授权申请失败') } finally { creating.value = false } }
onMounted(load)
</script>

<template>
  <div class="page-head"><div><span class="section-kicker">ACCESS / CHAIN OF CUSTODY</span><h1>档案授权</h1><p>申请、审批、使用和归还都留下时间与责任人记录。</p></div><el-button type="primary" class="action-button" @click="showCreate = true"><el-icon><Lock /></el-icon>新建授权申请</el-button></div>
  <section class="surface-panel table-panel"><div class="filter-row"><el-select v-model="filters.status" clearable placeholder="全部状态" class="compact-select"><el-option v-for="(label, value) in statusLabel" :key="value" :label="label" :value="value" /></el-select><el-button type="primary" @click="page = 1; load()"><el-icon><Refresh /></el-icon>刷新</el-button><span class="filter-total">共 {{ data.total }} 条</span></div><el-table v-loading="loading" :data="data.items" class="data-table" empty-text="暂无授权申请"><el-table-column prop="applicationNo" label="申请编号" min-width="220"><template #default="scope"><code class="employee-code">{{ scope.row.applicationNo }}</code></template></el-table-column><el-table-column prop="purpose" label="申请用途" min-width="220" show-overflow-tooltip /><el-table-column prop="useType" label="使用方式" width="120" /><el-table-column prop="dueAt" label="归还截止" width="180"><template #default="scope"><span :class="new Date(scope.row.dueAt) < new Date() && scope.row.status === 'IN_USE' ? 'text-risk' : ''"><el-icon><Clock /></el-icon> {{ new Date(scope.row.dueAt).toLocaleString('zh-CN') }}</span></template></el-table-column><el-table-column prop="status" label="状态" width="140"><template #default="scope"><el-tag :type="scope.row.status === 'ABNORMAL' ? 'danger' : scope.row.status === 'IN_USE' ? 'warning' : scope.row.status === 'RETURNED' ? 'success' : 'info'" effect="plain">{{ statusLabel[scope.row.status] || scope.row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="200" fixed="right"><template #default="scope"><el-button v-if="scope.row.status === 'PENDING_APPROVAL'" link type="success" @click="action(scope.row, 'approve')"><el-icon><Check /></el-icon>授权</el-button><el-button v-if="scope.row.status === 'APPROVED'" link type="primary" @click="action(scope.row, 'use')">开始使用</el-button><el-button v-if="scope.row.status === 'IN_USE'" link type="warning" @click="returnItem(scope.row)"><el-icon><Refresh /></el-icon>归还</el-button></template></el-table-column></el-table><div class="table-footer"><span>第 {{ page }} 页</span><el-pagination v-model:current-page="page" layout="prev, pager, next" :page-size="10" :total="data.total" @current-change="load" /></div></section>
  <el-dialog v-model="showCreate" title="新建档案授权申请" width="460px"><el-form label-position="top"><el-form-item label="申请用途"><el-input v-model="createForm.purpose" placeholder="例如：年度审计查阅" /></el-form-item><el-form-item label="使用方式"><el-select v-model="createForm.useType"><el-option label="查阅" value="READ" /><el-option label="借用" value="BORROW" /><el-option label="移交" value="HANDOVER" /></el-select></el-form-item><el-form-item label="档案版本 ID"><el-input v-model="createForm.versionIds" placeholder="多个 ID 用逗号分隔" /></el-form-item><el-form-item label="开始时间"><el-input v-model="createForm.startAt" type="datetime-local" /></el-form-item><el-form-item label="归还截止"><el-input v-model="createForm.dueAt" type="datetime-local" /></el-form-item></el-form><template #footer><el-button @click="showCreate = false">取消</el-button><el-button type="primary" :loading="creating" @click="createAccess">提交申请</el-button></template></el-dialog>
</template>
