<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowRight, CircleCheck, Clock, Document, Reading, Warning } from '@element-plus/icons-vue'
import { request, type StatisticsOverview } from '../api/http'

const loading = ref(true)
const error = ref('')
const stats = ref<StatisticsOverview>({ employeeCount: 0, completeArchiveCount: 0, archiveCount: 0, archiveCompleteness: 0, workflowCount: 0, pendingWorkflowCount: 0, activeAccessCount: 0, abnormalAccessCount: 0, ocrSucceededCount: 0, ocrFailedCount: 0, ocrReviewCount: 0, averageOcrDurationMs: 0, generatedAt: '' })
async function load() { loading.value = true; error.value = ''; try { stats.value = await request<StatisticsOverview>({ url: '/statistics/overview' }) } catch (e) { error.value = e instanceof Error ? e.message : '统计数据暂时不可用'; ElMessage.error(error.value) } finally { loading.value = false } }
onMounted(load)
</script>

<template>
  <div class="page-head"><div><span class="section-kicker">OVERVIEW / 现场状态</span><h1>业务总览</h1><p>今天的档案与流程，集中在这里快速判断。</p></div><el-button class="quiet-button" :loading="loading" @click="load"><el-icon><Reading /></el-icon>刷新数据</el-button></div>
  <el-alert v-if="error" type="warning" :closable="false" show-icon title="统计接口暂时不可用，仍可继续浏览其他模块" class="inline-alert" />
  <div class="metric-grid" v-loading="loading"><article class="metric-card ink"><span class="metric-label">在职员工</span><strong>{{ stats.employeeCount }}</strong><small>当前数据范围内</small><el-icon><CircleCheck /></el-icon></article><article class="metric-card"><span class="metric-label">档案完整率</span><strong>{{ (stats.archiveCompleteness * 100).toFixed(0) }}<sup>%</sup></strong><small>{{ stats.completeArchiveCount }} / {{ stats.archiveCount }} 份完整</small><div class="metric-bar"><i :style="{ width: `${Math.min(100, stats.archiveCompleteness * 100)}%` }" /></div></article><article class="metric-card"><span class="metric-label">待处理流程</span><strong>{{ stats.pendingWorkflowCount }}</strong><small>全部流程 {{ stats.workflowCount }} 条</small><el-icon><Clock /></el-icon></article><article class="metric-card risk"><span class="metric-label">异常授权</span><strong>{{ stats.abnormalAccessCount }}</strong><small>进行中 {{ stats.activeAccessCount }} 条</small><el-icon><Warning /></el-icon></article></div>
  <div class="dashboard-columns"><section class="surface-panel"><div class="panel-heading"><div><span class="section-kicker">OCR QUALITY</span><h2>OCR 识别质量</h2></div><RouterLink to="/employees" class="text-link">查看档案 <el-icon><ArrowRight /></el-icon></RouterLink></div><div class="quality-row"><div class="donut" :style="{ '--score': `${stats.ocrSucceededCount + stats.ocrFailedCount ? Math.round(stats.ocrSucceededCount / (stats.ocrSucceededCount + stats.ocrFailedCount) * 100) : 0}%` }"><span>{{ stats.ocrSucceededCount + stats.ocrFailedCount ? Math.round(stats.ocrSucceededCount / (stats.ocrSucceededCount + stats.ocrFailedCount) * 100) : 0 }}<small>%</small></span></div><div class="quality-list"><div><span class="dot green" />识别成功<strong>{{ stats.ocrSucceededCount }}</strong></div><div><span class="dot amber" />需要复核<strong>{{ stats.ocrReviewCount }}</strong></div><div><span class="dot red" />识别失败<strong>{{ stats.ocrFailedCount }}</strong></div></div></div></section><section class="surface-panel attention-panel"><div class="panel-heading"><div><span class="section-kicker">ACTION QUEUE</span><h2>待处理事项</h2></div><RouterLink to="/workflows" class="text-link">进入流程 <el-icon><ArrowRight /></el-icon></RouterLink></div><div class="queue-item"><span class="queue-icon amber"><Clock /></span><div><strong>{{ stats.pendingWorkflowCount }} 条人事流程等待审批</strong><small>按部门负责人和人事复核节点处理</small></div></div><div class="queue-item"><span class="queue-icon red"><Warning /></span><div><strong>{{ stats.abnormalAccessCount }} 条档案授权存在异常</strong><small>检查超期归还与盘点差异</small></div></div><div class="queue-item"><span class="queue-icon blue"><Document /></span><div><strong>{{ stats.ocrReviewCount }} 份材料需要 OCR 复核</strong><small>低置信度字段不会覆盖原始证据</small></div></div></section></div>
</template>
