<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { CircleCheck, Plus, Warning } from '@element-plus/icons-vue'
import { request, type InventoryTask, type Page } from '../api/http'
const versionIds = ref(''); const creating = ref(false); const created = ref<{ taskNo: string; status: string } | null>(null); const tasks = ref<Page<InventoryTask>>({ items: [], total: 0, page: 1, pageSize: 10 })
async function load() { try { tasks.value = await request<Page<InventoryTask>>({ url: '/inventory-tasks', params: { page: 1, pageSize: 10 } }) } catch (e) { ElMessage.error(e instanceof Error ? e.message : '盘点任务加载失败') } }
async function create() { const ids = versionIds.value.split(',').map((id) => Number(id.trim())).filter(Boolean); if (!ids.length) return ElMessage.warning('请输入要盘点的档案版本 ID'); creating.value = true; try { created.value = await request<{ taskNo: string; status: string }>({ url: '/inventory-tasks', method: 'POST', data: { versionIds: ids } }); ElMessage.success('盘点任务已创建'); load() } catch (e) { ElMessage.error(e instanceof Error ? e.message : '盘点任务创建失败') } finally { creating.value = false } }
load()
</script>

<template><div class="page-head"><div><span class="section-kicker">INVENTORY / EXCEPTION CONTROL</span><h1>盘点异常</h1><p>以档案版本为单位核对实际状态，未解决的差异不能完成盘点。</p></div><el-button type="primary" class="action-button" @click="create"><el-icon><Plus /></el-icon>创建盘点任务</el-button></div><div class="inventory-columns"><section class="surface-panel inventory-guide"><span class="section-kicker">CLOSURE RULE</span><h2>盘点闭环</h2><div class="flow-step"><span class="step-no">01</span><div><strong>创建任务</strong><small>选择档案版本快照</small></div></div><div class="flow-line" /><div class="flow-step"><span class="step-no">02</span><div><strong>现场核对</strong><small>记录实际版本与状态</small></div></div><div class="flow-line" /><div class="flow-step"><span class="step-no">03</span><div><strong>解决差异</strong><small>补件、修复或登记异常</small></div></div><div class="flow-line" /><div class="flow-step"><span class="step-no done">04</span><div><strong>归档完成</strong><small>所有差异已闭环</small></div></div></section><section class="surface-panel inventory-create"><div class="panel-heading"><div><span class="section-kicker">NEW INVENTORY</span><h2>发起一次盘点</h2></div><el-icon class="panel-symbol"><Warning /></el-icon></div><el-form label-position="top"><el-form-item label="档案版本 ID"><el-input v-model="versionIds" placeholder="例如：101, 102, 103" /></el-form-item><el-button type="primary" :loading="creating" @click="create">创建并进入草稿</el-button></el-form><div v-if="created" class="created-result"><el-icon><CircleCheck /></el-icon><div><strong>{{ created.taskNo }}</strong><small>状态：{{ created.status }}</small></div></div><div class="task-list"><span class="section-kicker">TASKS</span><div v-for="task in tasks.items" :key="task.id" class="task-row"><code>{{ task.taskNo }}</code><el-tag effect="plain">{{ task.status }}</el-tag></div><el-empty v-if="!tasks.items.length" description="暂无盘点任务" :image-size="45" /></div></section></div></template>
