<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Check, EditPen, Picture, WarningFilled } from '@element-plus/icons-vue'
import { request, type OcrResult } from '../api/http'

const route = useRoute(); const loading = ref(true); const result = ref<OcrResult | null>(null); const editing = ref(''); const editValue = ref(''); const editReason = ref('')
async function load() { loading.value = true; try { result.value = await request<OcrResult>({ url: `/archive/versions/${route.params.versionId}/ocr-result` }) } catch (e) { ElMessage.error(e instanceof Error ? e.message : 'OCR 结果加载失败') } finally { loading.value = false } }
function beginEdit(field: OcrResult['fields'][number]) { editing.value = field.fieldCode; editValue.value = field.value; editReason.value = '' }
async function save(fieldCode: string) { if (!editValue.value.trim()) return ElMessage.warning('修订值不能为空'); try { result.value = await request<OcrResult>({ url: `/archive/ocr-bindings/${result.value?.bindingId}/fields/${fieldCode}`, method: 'PUT', data: { value: editValue.value, reason: editReason.value } }); editing.value = ''; ElMessage.success('字段修订已记录') } catch (e) { ElMessage.error(e instanceof Error ? e.message : '字段修订失败') } }
onMounted(load)
</script>

<template>
  <div class="page-head"><div><span class="section-kicker">OCR REVIEW / HUMAN IN THE LOOP</span><h1>识别结果复核</h1><p>保留原始文本块，低置信度或格式校验失败字段需要人工确认。</p></div><el-tag v-if="result" :type="result.reviewRequired ? 'warning' : 'success'" size="large" effect="plain"><el-icon><WarningFilled v-if="result.reviewRequired" /><Check v-else /></el-icon>{{ result.reviewRequired ? '需要人工复核' : '已通过校验' }}</el-tag></div>
  <div class="ocr-layout" v-loading="loading"><section class="surface-panel evidence-panel"><div class="panel-heading"><div><span class="section-kicker">EVIDENCE / ORIGINAL</span><h2>检测框预览</h2></div><el-button text><el-icon><Picture /></el-icon>打开原图</el-button></div><div class="preview-placeholder"><div class="scan-grid"><span v-for="i in 12" :key="i" /></div><div class="preview-label">OCR 证据预览<small>原图与检测框由服务端受控代理</small></div></div><div class="text-blocks"><span v-for="block in result?.textBlocks || []" :key="`${block.pageNo}-${block.text}`">{{ block.text }} <b>{{ (block.confidence * 100).toFixed(0) }}%</b></span><el-empty v-if="!result?.textBlocks?.length" description="暂无文本块" :image-size="50" /></div></section><section class="surface-panel field-panel"><div class="panel-heading"><div><span class="section-kicker">MAPPED FIELDS</span><h2>业务字段</h2></div><span class="field-count">{{ result?.fields.length || 0 }} fields</span></div><div class="field-list"><div v-for="field in result?.fields || []" :key="field.fieldCode" class="field-row" :class="{ review: field.reviewRequired }"><div class="field-meta"><code>{{ field.fieldCode }}</code><span :class="field.reviewRequired ? 'confidence low' : 'confidence'">{{ (field.confidence * 100).toFixed(0) }}%</span></div><div v-if="editing === field.fieldCode" class="edit-line"><el-input v-model="editValue" /><el-input v-model="editReason" placeholder="修订原因（可选）" /><el-button type="primary" @click="save(field.fieldCode)">保存</el-button><el-button @click="editing = ''">取消</el-button></div><div v-else class="value-line"><strong>{{ field.value || '未识别' }}</strong><el-tag size="small" :type="field.validationStatus === 'PASSED' ? 'success' : 'warning'" effect="plain">{{ field.validationStatus === 'PASSED' ? '格式通过' : field.validationMessage || '待复核' }}</el-tag><el-button text title="修订字段" @click="beginEdit(field)"><el-icon><EditPen /></el-icon></el-button></div></div><el-empty v-if="!result?.fields.length" description="OCR 尚未返回业务字段" :image-size="60" /></div><div class="revision-footer">已记录 {{ result?.revisions.length || 0 }} 次人工修订</div></section></div>
</template>
