<template>
  <div>
    <div class="page-heading"><div><p class="eyebrow">Archive / Inventory</p><h1>盘点与异常</h1><p class="heading-copy">按范围建立盘点任务，逐项核对版本和实际状态。</p></div><label class="inline-load"><span>加载任务</span><input v-model.number="lookupId" type="number" min="1" placeholder="任务 ID" /><el-button text :icon="Search" :disabled="!lookupId" aria-label="加载盘点任务" title="加载盘点任务" @click="loadTask" /></label></div>
    <div class="workflow-layout inventory-layout">
      <section class="paper-panel form-panel"><div class="panel-heading"><div><p class="eyebrow">Inventory batch</p><h2>创建盘点任务</h2></div><span class="panel-index">CHECK</span></div><form class="operation-form" @submit.prevent="createTask"><div class="form-grid two-columns"><label class="form-field"><span>盘点范围</span><select v-model="form.scopeType"><option value="EMPLOYEE">员工</option><option value="DEPARTMENT">部门</option><option value="DOCUMENT_TYPE">材料类型</option><option value="ALL">全部档案</option></select></label><label class="form-field"><span>范围值</span><input v-model="form.scopeValue" type="text" placeholder="员工/部门/材料类型 ID" /></label></div><div class="item-editor"><div class="item-editor-heading"><span>待盘点材料</span><button type="button" class="text-action" @click="addItem"><el-icon><Plus /></el-icon>新增一项</button></div><div v-for="(item, index) in form.items" :key="index" class="item-editor-row"><input v-model.number="item.archiveDocumentId" type="number" min="1" required placeholder="材料 ID" /><input v-model.number="item.expectedVersionId" type="number" min="1" required placeholder="期望版本 ID" /><button v-if="form.items.length > 1" type="button" class="icon-action" aria-label="删除盘点材料" title="删除盘点材料" @click="removeItem(index)"><el-icon><Delete /></el-icon></button></div></div><div v-if="error" class="inline-error">{{ error }}</div><div class="form-actions"><el-button type="primary" native-type="submit" :loading="working" :icon="Plus">创建任务</el-button><el-button text @click="resetForm">清空</el-button></div></form></section>
      <section class="paper-panel workflow-detail-panel"><div class="panel-heading"><div><p class="eyebrow">Inventory status</p><h2>盘点明细</h2></div><span v-if="task" class="state-chip" :class="stateClass(task.status)">{{ statusLabel(task.status) }}</span></div><div v-if="loading" class="empty-state">正在加载盘点任务</div><div v-else-if="!task" class="workflow-empty"><el-icon><Finished /></el-icon><strong>等待一条盘点任务</strong><span>创建任务后，可开始盘点并逐项记录差异。</span></div><div v-else class="workflow-detail"><div class="request-id-row"><span>{{ task.taskNo }}</span><span>任务 ID {{ task.id }}</span></div><dl class="detail-grid"><div><dt>盘点范围</dt><dd>{{ scopeLabel(task.scopeType) }}</dd></div><div><dt>范围值</dt><dd>{{ task.scopeValue || '全量' }}</dd></div><div><dt>材料数量</dt><dd>{{ task.items.length }} 项</dd></div><div><dt>已核对</dt><dd>{{ checkedCount }} / {{ task.items.length }}</dd></div></dl><div class="inventory-items"><article v-for="item in task.items" :key="item.id" class="inventory-item"><div class="inventory-item-heading"><div><strong>材料 {{ item.archiveDocumentId }}</strong><span>期望版本 v{{ item.expectedVersionId }}</span></div><span v-if="item.checkedAt" class="state-chip" :class="item.differenceType === 'NONE' ? 'success' : 'danger'">{{ differenceLabel(item.differenceType) }}</span></div><div v-if="item.checkedAt" class="inventory-result">实际状态：{{ actualStatusLabel(item.actualStatus) }} · {{ formatDate(item.checkedAt) }}<p v-if="item.differenceDescription">{{ item.differenceDescription }}</p></div><div v-else-if="task.status === 'IN_PROGRESS'" class="check-form"><select v-model="checks[item.id].actualStatus"><option value="PRESENT">在库</option><option value="MISSING">缺失</option><option value="DAMAGED">损坏</option></select><input v-model.number="checks[item.id].actualVersionId" type="number" min="1" placeholder="实际版本 ID" :disabled="checks[item.id].actualStatus !== 'PRESENT'" /><input v-model="checks[item.id].differenceDescription" type="text" placeholder="差异说明（异常必填）" /><el-button text :icon="Check" :loading="working" aria-label="保存盘点结果" title="保存盘点结果" @click="checkItem(item)" /></div><div v-else class="muted-copy">任务尚未开始</div></article></div><div v-if="task.status === 'ABNORMAL'" class="resolve-box"><label class="form-field"><span>异常处理结论</span><textarea v-model="resolution" rows="3" placeholder="填写缺失、损坏或版本不一致的处理结果"></textarea></label><el-button type="primary" :loading="working" :icon="CircleCheck" @click="resolveTask">完成异常处理</el-button></div><div class="detail-actions"><el-button v-if="task.status === 'DRAFT'" type="primary" :icon="VideoPlay" :loading="working" @click="startTask">开始盘点</el-button><el-button v-if="task.status === 'IN_PROGRESS' && checkedCount === task.items.length" type="primary" :icon="Finished" :loading="working" @click="completeTask">完成盘点</el-button><span v-if="task.status === 'COMPLETED'" class="success-note"><el-icon><CircleCheck /></el-icon>盘点任务已归档</span></div></div></section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Check, CircleCheck, Delete, Finished, Plus, Search, VideoPlay } from '@element-plus/icons-vue'
import { checkInventoryItem, completeInventory, createInventory, getInventory, resolveInventory, startInventory } from '@/api/workflow'
import type { InventoryItem, InventoryTask } from '@/types/api'
const form = reactive({ scopeType: 'EMPLOYEE', scopeValue: '', items: [{ archiveDocumentId: 0, expectedVersionId: 0 }] })
const checks = reactive<Record<number, { actualStatus: string; actualVersionId: number | null; differenceDescription: string }>>({})
const task = ref<InventoryTask | null>(null); const lookupId = ref<number | null>(null); const loading = ref(false); const working = ref(false); const error = ref(''); const resolution = ref('')
const checkedCount = computed(() => task.value?.items.filter((item) => Boolean(item.checkedAt)).length || 0)
function addItem() { form.items.push({ archiveDocumentId: 0, expectedVersionId: 0 }) }
function removeItem(index: number) { form.items.splice(index, 1) }
async function createTask() { working.value = true; error.value = ''; try { task.value = await createInventory({ scopeType: form.scopeType, scopeValue: form.scopeValue.trim(), items: form.items.map((item) => ({ archiveDocumentId: item.archiveDocumentId, expectedVersionId: item.expectedVersionId })) }); initializeChecks(); ElMessage.success('盘点任务已创建') } catch (e) { error.value = e instanceof Error ? e.message : '盘点任务创建失败' } finally { working.value = false } }
async function loadTask() { if (!lookupId.value) return; loading.value = true; error.value = ''; try { task.value = await getInventory(lookupId.value); initializeChecks() } catch (e) { error.value = e instanceof Error ? e.message : '盘点任务加载失败'; task.value = null } finally { loading.value = false } }
async function startTask() { await mutate(() => startInventory(task.value!.id), '盘点已开始') }
async function checkItem(item: InventoryItem) { const check = checks[item.id]; if (!check) return; working.value = true; error.value = ''; try { await checkInventoryItem(task.value!.id, item.id, { actualStatus: check.actualStatus, actualVersionId: check.actualStatus === 'PRESENT' ? check.actualVersionId : null, differenceDescription: check.differenceDescription.trim() }); task.value = await getInventory(task.value!.id); initializeChecks(); ElMessage.success('盘点结果已保存') } catch (e) { error.value = e instanceof Error ? e.message : '盘点结果保存失败' } finally { working.value = false } }
async function completeTask() { await mutate(() => completeInventory(task.value!.id), '盘点已完成') }
async function resolveTask() { if (!resolution.value.trim()) { error.value = '请填写异常处理结论'; return }; await mutate(() => resolveInventory(task.value!.id, resolution.value.trim()), '异常处理已完成') }
async function mutate(action: () => Promise<InventoryTask>, message: string) { working.value = true; error.value = ''; try { task.value = await action(); initializeChecks(); ElMessage.success(message) } catch (e) { error.value = e instanceof Error ? e.message : '任务状态更新失败' } finally { working.value = false } }
function initializeChecks() { if (!task.value) return; task.value.items.forEach((item) => { if (!checks[item.id]) checks[item.id] = { actualStatus: 'PRESENT', actualVersionId: item.expectedVersionId, differenceDescription: '' } }) }
function resetForm() { form.scopeType = 'EMPLOYEE'; form.scopeValue = ''; form.items.splice(0, form.items.length, { archiveDocumentId: 0, expectedVersionId: 0 }); error.value = '' }
function scopeLabel(value: string) { return ({ EMPLOYEE: '员工', DEPARTMENT: '部门', DOCUMENT_TYPE: '材料类型', ALL: '全部档案' }[value] || value) }
function statusLabel(value: string) { return ({ DRAFT: '草稿', IN_PROGRESS: '盘点中', ABNORMAL: '待处理异常', COMPLETED: '已完成' }[value] || value) }
function actualStatusLabel(value: string | null) { return ({ PRESENT: '在库', MISSING: '缺失', DAMAGED: '损坏' }[value || ''] || '未记录') }
function differenceLabel(value: string | null) { return ({ NONE: '正常', MISSING: '缺失', DAMAGED: '损坏', VERSION_MISMATCH: '版本不一致' }[value || ''] || value || '异常') }
function stateClass(value: string) { return value === 'COMPLETED' ? 'success' : value === 'ABNORMAL' ? 'danger' : 'pending' }
function formatDate(value: string | null) { return value ? value.replace('T', ' ').slice(0, 16) : '—' }
</script>
