spring:
  config:
    activate:
      on-profile: test
  flyway:
    clean-disabled: false

app:
  datasource:
    write:
      url: ${MYSQL_WRITE_URL:jdbc:mysql://127.0.0.1:13306/archive_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
      username: ${MYSQL_USERNAME:hr}
      password: ${MYSQL_PASSWORD:change-me-application-password}
    read:
      url: ${MYSQL_READ_URL:jdbc:mysql://127.0.0.1:13307/archive_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
      username: ${MYSQL_USERNAME:hr}
      password: ${MYSQL_PASSWORD:change-me-application-password}
