CREATE DATABASE IF NOT EXISTS identity_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS archive_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS workflow_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
